package constants

const (
	EMAIL_ADMIN_MEOWHASISWA = "meowhasiswa.admin@meowhasiswa.com"

	USER_ROLE  = "USER"
	ADMIN_ROLE = "ADMIN"
)

const (
	LIKE_ACTION      = "LIKE"
	UNLIKE_ACTION    = "UNLIKE"
	DISLIKE_ACTION   = "DISLIKE"
	UNDISLIKE_ACTION = "UNDISLIKE"

	UNI_RATING_PRO = "PRO"
	UNI_RATING_CON = "CON"
)

const (
	DEFAULT_INCREMENT_REPUTATION = 5
	DEFAULT_DECREMENT_REPUTATION = 5
)

// notification
const (
	EVENT_TYPE_KEY = "event_type"
	APP_ROUTE_KEY  = "route"

	COMMENT_ON_THREAD_EVENT            = "COMMENT_ON_THREAD"
	COMMENT_ON_SUBSCRIBED_THREAD_EVENT = "COMMENT_ON_SUSBCRIBED_THREAD"
)

// email
const (
	TYPE_VERIFY_EMAIL   = "VERIFY_EMAIL"
	TYPE_RESET_PASSWORD = "RESET_PASSWORD"
)
